# tree format
Config:
 General:
 #Allowed LOGMODEs
 # INFO, WARNING, ERROR, CRITICAL, DEBUG
  LOGMODE: INFO
#  LOGFILE: ./gpio2mqtt.log
  LOGFILE: /var/log/gpio2mqtt.log
  
 Broker:
  MQTT_HOST: localhost
  MQTT_PORT: 1883
  MQTT_CHANNEL: /OPENHAB
  
 Device1:
   RASPBERRY_REV: 1
   I2C_ADDRESS: 0x26
   DEVICE: MCP23017
 #  DEVICE: SIMULATOR
   MQTT_CHANNEL: /OPENHAB/DEVICE1

   Port0:
    NAME: GPIO100
    HW_ID: 0
    DIRECTION: IN
    ON_VALUE: OPEN
    OFF_VALUE: CLOSED
    MODE: GPIO

   Port1:
    NAME: GPIO101
    HW_ID: 1
    DIRECTION: IN
    ON_VALUE: OPEN
    OFF_VALUE: CLOSED
    MODE: GPIO
    
   Port2:
    NAME: DEBOUNCE102
    HW_ID: 2
    DIRECTION: IN
    MODE: DEBOUNCE
    
   Port8:
    NAME: GPIO108
    HW_ID: 8
    DIRECTION: OUT
    ON_VALUE: ON
    OFF_VALUE: OFF
    MODE: GPIO

   Port9:
    NAME: GPIO109
    HW_ID: 9
    DIRECTION: OUT
    ON_VALUE: ON
    OFF_VALUE: OFF
    MODE: GPIO
    
   Port10:
    NAME: FLASH110
    HW_ID: 10
 #   DIRECTION: OUT
    MAX: 10
    MIN: 0.5
    PORT_DEFAULT: 0
    MODE: FLASH
    
   Port11:
    NAME: FLASH111
    HW_ID: 11
 #   DIRECTION: OUT
    MAX: 10
    MIN: 0.5
    PORT_DEFAULT: 0
    MODE: FLASH
    
 Device2:
   RASPBERRY_REV: 1
   I2C_ADDRESS: 0x20
   DEVICE: MCP23017
#   DEVICE: Simulator
   MQTT_CHANNEL: /OPENHAB/DEVICE2

   Port0:
    NAME: GPIO200
    HW_ID: 0
    DIRECTION: OUT
    ON_VALUE: ON
    OFF_VALUE: OFF
    MODE: GPIO

   Port1:
    NAME: GPIO201
    HW_ID: 1
    DIRECTION: OUT
    ON_VALUE: ON
    OFF_VALUE: OFF
    MODE: GPIO
    
   Port2:
    NAME: FLASH202
    HW_ID: 2
 #   DIRECTION: OUT
    MAX: 15
    MIN: 0.5
    PORT_DEFAULT: 0
    MODE: FLASH
    
   Port3:
    NAME: FLASH203
    HW_ID: 3
 #   DIRECTION: OUT
    MAX: 15
    MIN: 0.5
    PORT_DEFAULT: 0
    MODE: FLASH
    
   Port8:
    NAME: GPIO208
    HW_ID: 8
    DIRECTION: IN
    ON_VALUE: ON
    OFF_VALUE: OFF
    MODE: GPIO
    
   Port9:
    NAME: GPIO209
    HW_ID: 9
    DIRECTION: IN
    ON_VALUE: ON
    OFF_VALUE: OFF
    MODE: GPIO
   
 Device3:
 #  RASPBERRY_REV: 1
 #  I2C_ADDRESS: 0x20
 #  DEVICE: MCP23017
#   DEVICE: Simulator
   DEVICE: RASPBERRY
   MQTT_CHANNEL: /OPENHAB/DEVICE3

   Port0:
    NAME: GPIO324
    HW_ID: 24
    DIRECTION: OUT
    ON_VALUE: ON
    OFF_VALUE: OFF
    MODE: GPIO

   Port1:
    NAME: GPIO325
    HW_ID: 24
    DIRECTION: OUT
    ON_VALUE: ON
    OFF_VALUE: OFF
    MODE: GPIO
    